  const Product = [
    {
      id: 1,
      name: "AUNTSFIELD SINGLE VINEYARD SOUTHERN VALLEYS PINOT NOIR, 2020",
      country: "NEW ZEALAND ",
      category:"Red Wine",
      alcohol:"14 ",
      desc:"Rich, silky and supple on the palate as only exceptional Pinot Noir can be. Powerful with lifted aromatics and a profile that leans towards dark fruits.Ripe black plums, olives and dark chocolate with notes of cigar box and liquorice on a long finish      ",
      img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/AuntsfieldPinotNoirNewZealandRedWineWhelehansWines_5000x.png?v=1669387261",
      price:34,
    },
    {
        id: 2,
        name: "AUNTSFIELD SINGLE VINEYARD SAUVIGNON BLANC, 2022",
        country: "NEW ZEALAND",
        category:"Red Wine",
        alcohol:"13 ",
        desc:"Vibrant, fresh and aromatically enticing with a smoky seam running through it. Intense flavour of passionfruit, guava and gooseberry mix with a hint of white pepper, green herbs and crushed ferns,Medium-bodied and dry with mouth-watering intensity and a textured, mineral edge on a long and clean finish  ",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/AuntsfieldSauvignonBlancNewZealandWhiteWineWhelehansWines_5000x.jpg?v=1669386773",
        price:23,
      },
      {
        id: 3,
        name: "THIERRY MORTET GEVREY-CHAMBERTIN, 2018",
        country: "FRANCE",
        category:"Red Wine",
        alcohol:"13 ",
        desc:"Thierry Mortet farms 7.3ha over four communes which have been certified organic since 2007. The vines for this wine are 15-60 years old and produce about 15,000 bottles. ",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/ThierryMortetGevreyChambertinFranceWineWhelehansWines_5000x.jpg?v=1669977273",
        price:72,
      },
      {
        id: 4,
        name: "DOMAINE HOSPICES DE BEAUJEU RÉGNIÉ, 2020",
        country: "FRANCE",
        category:"Red Wine",
        alcohol:"13 ",
        desc:"Purplish red colour, nose of candied red fruits with aromas of raspberry. Mouth full of fresh roundness where we find notes of Morello cherry and blackcurrant. Nice length and smooth finish.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/HospicesdeBeaujeuRegnieRedWineFranceWhelehansWines_5000x.jpg?v=1668508382",
        price:24,
      },
      {
        id: 5,
        name: "ROBERTO SAROTTO BARBERA D'ASTI, 2021",
        country: "ITALY",
        category:"Red Wine",
        alcohol:"14.5 ",
        desc:"A wonderful, quintessential light red. Light to medium-bodied in style this Barbera d'Asti displays blackberry and dark cherry aromas. The palate is ripe, rounded and supple with red fruit flavours, spice and a hint of vanilla. A red wine you could serve slightly chilled in the warmer summer months.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/RobertoSarottoBarberad_AstiromboRedWineItalyWhelehansWines_5000x.jpg?v=1668784737",
        price:19,
      },
      {
        id: 6,
        name: "TORMARESCA TORCICODA PRIMITIVO DEL SALENTO IGT, 2019",
        country: "ITALY",
        category:"Red Wine",
        alcohol:"15.5 ",
        desc:"Selected from old Primitivo vines, head-pruned bush vines, and from newer cordon-trained vineyards, both cultivated at the Maìme estate at San Pietro Vernotico (Province of Brindisi).",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/TormarescaTorcicodaPrimitivodelSalentoRedWineItalyWhelehansWines_5000x.jpg?v=1668010812",
        price:31,
      },
      {
        id: 7,
        name: "CURATOLO ARINI NERO DAVOLA, 2019",
        country: "ITALY",
        category:"Red Wine",
        alcohol:"13.5 ",
        desc:"The vineyards are located in central Sicily, at about 500 metres above sea level. Deep ruby in colour, with purple hints and notes of violets and red cherries, plums and hints of white pepper.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/CuratoloAriniNerod_AvolaRedWineItalyWhelehansWines_6ec3abd8-f838-4508-a23a-f7fea937d3fa_5000x.jpg?v=1667391422",
        price:29,
      },
      {
        id: 8,
        name: "BODEGAS DE LA MARQUESA VALSERRANO CRIANZA, 2018",
        country: "SPAIN",
        category:"Red Wine",
        alcohol:"14 ",
        desc:"From one of the top-10 traditional Rioja producers (Tim Atkin MW), this family run estate has 5 had 5 generations making wine for over 100 years. The average age of the vines is 30 years old. The family belief is that the quality of the wines is born in the vineyards.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/ValserranoCrianzaSpainWineWhelehansWines_5000x.png?v=1667903409",
        price:21,
      },
      {
        id: 9,
        name: "BODEGAS DE LA MARQUESA VALSERRANO RESERVA - MAGNUM, 2016",
        country: "SPAIN",
        category:"Red Wine",
        alcohol:"14.5 ",
        desc:"From a vintage designated as very good, this is a fine example of Rioja at its captivating best. The blend of Tempranillo (90%) and Graciano is highly expressive with dried fruit, nutmeg and cherry aromas; full-bodied with mouth-filling juicy berry fruits and hints of toasted oak; lovely minty tones and a long, elegant finish.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/ValserranoReservaMagnumRiojaRedWineSpainWhelehansWines_5000x.png?v=1667908454",
        price:59,
      },
      {
        id: 10,
        name: "CHÂTEAU FABRE GASPARETS CORBIÈRES BOUTENAC, 2018",
        country: "FRANCE",
        category:"Red Wine",
        alcohol:"13.5 ",
        desc:"This bold Corbieres shows an intense ruby robe. The nose is firm and spicy with fine notes of sloe and blackcurrant. The palate is fresh with complex aromas of black fruit and spices. The delicate finish offers elegant tannins.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/ChateauFabreGasparetsFranceRedWineWhelehansWines_5000x.png?v=1667899947",
        price:28,
      },
      {
        id: 11,
        name: "DOMAINE POCHON CROZES-HERMITAGE - MAGNUM, 2019",
        country: "FRANCE",
        category:"Red Wine",
        alcohol:"14 ",
        desc:"Etienne Pochon is one of the insider secrets in the Northern Rhone. His family tree dates back to the late 1700’s where they have farmed and crafted some of the most thrilling wines in the Northern Rhone.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/PochonCrozehermitageRedWineFranceWhelehansWinesMagnum_5000x.png?v=1667901067",
        price:53,
      },
      {
        id: 12,
        name: "WILLIAM FEVRE 1ER CRU VAULORENT, 2018",
        country: "FRANCE",
        category:"White Wine",
        alcohol:"13 ",
        desc:"Green pear freshness edged with lemon marks out this wine's nose. The pear is rounder and riper on the palate but that freshness remains, leading to cooling, concentrated and chalky depth. It has elegance and lasting freshness—a triumph in 2018. Enjoy through 2040. Anne Krebiehl MW, Wine Enthusiast",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/WilliamFevreChablisValourentFranceWhiteWineWhelehansWines_5000x.png?v=1669977594",
        price:110,
      },
      {
        id: 13,
        name: "PRODUTTORI VINI MANDURIA ZIN FIANO SALENTO IGT, 2021",
        country: "ITALY",
        category:"White Wine",
        alcohol:"13 ",
        desc:"This wine shows off refreshing waves of hawthorn, broom and cedar and gives a balanced, fine and silky sip. Intense straw yellow in colour with green hues, the nose is curiously aromatic with passion fruit, ripe green apple and juicy pear fruit. On the palate it offers frehness matched perfectly with a slight rich texture. Long lasting finish with some citrus and cedar wood.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/ZinFianoItalyWineWhelehansWines_5000x.png?v=1669202011",
        price:21,
      },
      {
        id: 14,
        name: "LOUIS JADOT COUVENT DES JACOBINS BOURGOGNE BLANC, 2021",
        country: "FRANCE",
        category:"White Wine",
        alcohol:"12.5 ",
        desc:"From Louis Jadot winery: 'The production area for this wine is the whole of Burgundy. The Louis Jadot Bourgogne Chardonnay Couvent des Jacobins cuvée comes from a balanced blend of Côte d'Or, Chalonnais and Viré-Clessé best vineyards. Mâconnais grapes give freshness while Côte d'Or and Chalonnais give the wine structure.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/LouisJadotCouventdesJacobinsBourgogneBlancFranceWhiteWineWhelehansWines_5000x.png?v=1669135535",
        price:31,
      },
      {
        id: 15,
        name: "SLIDING HILL SAUVIGNON BLANC, 2022",
        country: "NEW ZEALAND",
        category:"White Wine",
        alcohol:"13 ",
        desc:"This is a well-concentrated and deep fruited Sauvignon Blanc with passionfruit and gooseberry flavours on a fine palate with fresh acidity.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/SlidingHillSauvignonBlancNewZealandWineWhelehansWines_5000x.jpg?v=1669386564",
        price:21,
      },
      {
        id: 16,
        name: "VIGNOBLES DE LA COULÉE DE SERRANT CLOS DE LA COULÉE DE SERRANT, 2020",
        country: "FRANCE",
        category:"White Wine",
        alcohol:"14.5 ",
        desc:"The Clos de la Coulée de Serrant is a singular appellation, located in the heart of the Savennières appellation, enjoying a climate not dissimilar to that of Burgundy. Nicolas Joly, a key defender of the use of biodynamics since 1985, uses no chemical fertilisers or pesticides, allowing this exceptional land to be fully expressed through its wines. It combines understanding of the almanac with respect to soil preparation, regeneration, and all the necessary vine care and maintenance required throughout the year.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/CouleedeServantsClosdeLaFranceWhiteWineWhelehansWiness_5000x.png?v=1669041690",
        price:123,
      },
      {
        id: 17,
        name: "VIGNOBLES DE LA COULÉE DE SERRANT SAVENNIÈRES LES VIEUX CLOS, 2020",
        country: "FRANCE",
        category:"White Wine",
        alcohol:"14.5 ",
        desc:"A biodynamic and very attractive Savennières wine boasting mature fruits and an ample, fresh and mineral body. A reference of the appellation.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/CouleedeSerrantSavennieresLesVieuxClosWhiteWineFranceWhelehansWines_5000x.png?v=1669041665",
        price:62,
      },
      {
        id: 18,
        name: "DOMAINE MARGUERITE DUPASQUIER RULLY, 2019",
        country: "FRANCE",
        category:"White Wine",
        alcohol:"14 ",
        desc:"This wine is ready-to-drink southern Burgundy Chardonnay with aromas of apple, vanilla, woodsmoke, nuts and citrus. It is dry with good fruit and a fresh acidity. Fairly full bodied, and long-finishing.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/MargueriteDupasquierRullyFranceWhiteWineWhleehansWines_5000x.jpg?v=1668510489",
        price:36,
      },
      {
        id: 19,
        name: "FAMILLE FABRE GRANDE COURTADE ALVARINHO, 2021",
        country: "FRANCE",
        category:"White Wine",
        alcohol:"14 ",
        desc:"On the nose, you will find notes of limoncello, juniper, and candied lemon. A tangy palate with mineral and spice.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/GrandeCourtadeFabreAlvarinhoWhiteWineFranceWhelehansWines_5000x.png?v=1667899545",
        price:21,
      },
      {
        id: 20,
        name: "CHÂTEAU VILLA BEL-AIR BLANC, 2018",
        country: "FRANCE",
        category:"White Wine",
        alcohol:"12.5 ",
        desc:"Citrus, apple and gooseberry nose. Bright vibrant acidity with long layers. - Panel Chair: Martin Moran MW , Co-Chair: Peter McCombie MW' - Silver, International Wine Challenge",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/ChateauVillaBel-AirBlancFranceWhiteWineWhelehansWines_5000x.jpg?v=1666621555",
        price:27,
      },
      {
        id: 21,
        name: "L. BÉNARD PITOIS PREMIER CRU GOURMANDISE DEMI-SEC, NV",
        country: "FRANCE",
        category:"Champagne",
        alcohol:"12 ",
        desc:"The Bénard-Pitois family started to produce Champagne in 1878. Now the third generation Michelle and Laurent Bénard-Louis continue the tradition and manage the family Domaine.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/BenardPitois-demisec_5000x.jpg?v=1667919860",
        price:43,
      },
      {
        id: 22,
        name: "POL ROGER BLANC DE BLANCS BRUT VINTAGE, 2013",
        country: "FRANCE",
        category:"Champagne",
        alcohol:"12.5 ",
        desc:"From Pol Roger winery: 'The 2013 Brut Blanc de Blancs is exclusively made from Chardonnays selected from the Grands Crus of the Côte des Blancs : Oiry, Chouilly, Cramant, Avize, Oger and Le Mesnil-sur-Oger. Produced in limited quantities, this Cuvée has been aged for 6 years in our cellars before being released onto the market.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/PolRoger2013FranceChampagneWhelehansWines_9db5d06d-af5f-4ce6-a9de-ca2bf5831c7e_5000x.jpg?v=1666086970",
        price:100,
      },
      {
        id: 23,
        name: "BOLLINGER SPECIAL CUVÉE BRUT - MAGNUM, NV",
        country: "FRANCE",
        category:"Champagne",
        alcohol:"12.5 ",
        desc:"Special Cuvée is the result of the delicate blending between harvest grapes and a majority of reserve wines, part of which have been aged in magnums for 5 to 15 years",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/BollingerChampagneFranceWhelehansWines_a3158a93-ea6c-4d40-800c-40c7e137517b_5000x.png?v=1665399012",
        price:152,
      },
      {
        id: 24,
        name: "VEUVE CLICQUOT LA GRANDE DAME BRUT, 2012",
        country: "FRANCE",
        category:"Champagne",
        alcohol:"12 ",
        desc:"La Grande Dame 2012 is both precise and delicate. He is playful, lively, laughing. This new vintage offers a strong minerality carried by the Pinot Noir, balanced by the freshness of the blend. Its aging potential is immense, it is a wine whose tasting makes me vibrate' Didier Mariotti, Cellar Master at Veuve Clicquot",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/VeuveClicquotGrandeDameBrutFranceChampagneWhelehansWines_5000x.jpg?v=1656519814",
        price:100,
      },
      {
        id: 25,
        name: "DOMAINE TOUR CAMPANETS COTEAUX D'AIX-EN-PROVENCE BOIS DES FÉES ROSÉ, 2021",
        country: "FRANCE",
        category:"Rosé Wine",
        alcohol:"13.5 ",
        desc:"Pale and copper-coloured this is more earthy and savoury than most Provence rosés. Medium-Bodied with strawberry, redberries and peach notes. Aromas of White flowers and a lingering, mouth-watering finish",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/CampanetsBoisdesFeesRoseFranceWineWhelehansWines_5000x.png?v=1657791370",
        price:29,
      },
      {
        id: 26,
        name: "CHÂTEAU DE FESLES ROSÉ D'ANJOU, 2021",
        country: "FRANCE",
        category:"Rosé Wine",
        alcohol:"10.5 ",
        desc:"Rosé d'Anjou has an attractive salmon-pink hue with garnet highlights. Aromatically rich with wild raspberries, redcurrants and cardamon. Mellow with a creamy texture on the palate with naunces of peach, blackberry and honeysuckle. The finish is a delight with a distinctive flavour of caramelized wild strawberries.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/ChateaudefeslesroseFranceWhelehansWines_5000x.jpg?v=1655116550",
        price:19,
      },
      {
        id: 27,
        name: "CHÂTEAU MIRAVAL CÔTES DE PROVENCE, 2021",
        country: "FRANCE",
        category:"Rosé Wine",
        alcohol:"13 ",
        desc:"A beautiful salmon pink coloured wine which brings one straight to Provence. Beautiful aromas of spring flowers and melon. A well-balanced wine balancing freshness and complexity. It is medium-bodied with a zesty long finish",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/MiravalRoseProvenceFranceWineWhelehansWines_5000x.jpg?v=1599647556",
        price:32,
      },
      {
        id: 28,
        name: "BOUVET-LADUBAY TRÉSOR BRUT BLANC, 2016",
        country: "FRANCE",
        category:"Sparkling Wine",
        alcohol:"12.5 ",
        desc:"This opulent Chenin Blanc & delightful Chardonnay Cuvée aged in oak barrels reveals a delicate structure : Brioche & Citrusy aromas, a creamy texture & well-balanced tannins.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/BouvetCremantTresorFranceSparklingWineWhelehansWines_5000x.jpg?v=1667920040",
        price:32,
      },
      {
        id: 29,
        name: "BOUVET-LADUBAY RUBIS EXCELLENCE, NV",
        country: "FRANCE",
        category:"Sparkling Wine",
        alcohol:"12.5 ",
        desc:"From the winery: 'Round and robust red sparkling made by Méthode Traditionnelle, Rubis is the ideal 'vino di meditazione', a delight to unwind and relax with. Bright and shimmering cherry red colour. Peony pink froth. Delightful aromas of ripe red berry fruits. The fine tannins are well balanced by a refreshing sparkle and the Demi-Sec dosage.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/BouvetLadubaySparklingRubisFranceWhelehansWInes_5000x.png?v=1666195614",
        price:29,
      },
      {
        id: 30,
        name: "ANNA SPINATO VALDOBBIADENE SUPERIORE DI CARTIZZE BRUT, NV",
        country: "ITALY",
        category:"Sparkling Wine",
        alcohol:"11 ",
        desc:"With a bright straw yellow color with clear grenish hints, this great prosecco releases fragrance of great intensity and aromaticity. Notes of white flowers, decana pear, yellow plum, and a mineral trail, almost of wet stone that recalls the territory. Enjoy an enveloping sip, juicy, full, with an incredible aroma that closes itself tightly",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/AnnaSpinatoProseccoSuperioreCartizzeSparklingWineItalyWhelehansWines_5000x.png?v=1663678759",
        price:49,
      },
      {
        id: 31,
        name: "LEITZ EINS ZWEI ZERO SPARKLING ROSÉ RIESLING, NV",
        country: "GERMANY",
        category:"No Alcohol",
        alcohol:"0 ",
        desc:"This non-alcoholic sparkling rosé is 100% made from pinot noir. The CO2 really balances out the residual sugar, making it appear drier than it it is. Because of that, it's even more wine-like! This refreshing sparkler exudes cool, red fruits and lean minerality.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/LeitzSparklingRoseGermanyWhelehansWines_5000x.png?v=1665586270",
        price:19,
      },
      {
        id: 32,
        name: "DOMAINE DE LA RECTORIE BANYULS CUVÉE THÉRÈSE REIG - 50CL, 2021",
        country: "FRANCE",
        category:"Dessert Wine",
        alcohol:"17.5 ",
        desc:"Aromas of prune and bitter cherry liqueur with some sweet spices help to lift the nose, some nutmeg and black pepper give it a spicy warming edge. The palate is very smooth and fruity, but not too sweet.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/DomainedelaRectorieThereseReigSweetWineBanylusWhelehansWines_5000x.jpg?v=1668523744",
        price:41,
      },
      {
        id: 33,
        name: "CHAMBERS ROSEWOOD VINEYARDS OLD VINE MUSCAT, NV",
        country: "AUSTRALIA",
        category:"Dessert Wine",
        alcohol:"18 ",
        desc:"Expect raisins and rose petal aromas combining with luscious palate consistent with the fruit aromas and the hint of wood age. The result is a rich, well balanced wine with depth of flavour to enjoy with cheese dishes or chocolate based desserts.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/BottleShot_15_5000x.png?v=1665578457",
        price:32,
      },
      {
        id: 34,
        name: "TURK GRUNER VELTLINER EISWEIN - HALF BOTTLE, 2017",
        country: "AUSTRIA",
        category:"Dessert Wine",
        alcohol:"9.5 ",
        desc:"Franz Turk is hailed as one of Austria's top winemakers and to date has won the trophy for 'Best Gruner Veltliner' and best 'Eiswein’ in Austria. Based in Kremstal this specialist producer has vineyards dating back to 1200's. This Gruner is absolutely best in class. It was from this vineyard Franz won the IWSC trophy for world's best 'Gruner Veltliner'!",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/TurkGrunerVeltinerEisweinAustriaWineWhelehansWines_5000x.png?v=1599226651",
        price:39,
      },
      {
        id: 35,
        name: "FEUDUCCIO PASSITO COLLINE TEATINE IGT 500ML, NV",
        country: "ITALY",
        category:"Dessert Wine",
        alcohol:"14.5 ",
        desc:"A blend of red grapes from three different vineyards, the grapes are harvested late, in November, and left to dry for a month on wattles.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/FeuduccioPassitoItalyRedWineWhelehansWines_5000x.jpg?v=1599663563",
        price:23,
      },
      {
        id: 36,
        name: "LEITZ EINS ZWEI ZERO SPARKLING RIESLING, NV",
        country: "GERMANY",
        category:"No Alcohol",
        alcohol:"0 ",
        desc:"This sparkling Riesling is a dealcoholised sparkling wine produced by award-winning German winemaker Johannes Leitz. He has used high quality Riesling grapes to produce a wine full of flavour, but which then goes through a gentle dealcoholisation method to produce a 0% alcohol free sparkling wine.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/Leitzsparkling_5000x.jpg?v=1590593511",
        price:19,
      },
      {
        id: 37,
        name: "SAUVION HAUT-POITOU SAUVIGNON BLANC, 2021",
        country: "FRANCE",
        category:"No Alcohol",
        alcohol:"0 ",
        desc:"A crisp, dry and well structured white reminiscent of the classic Sauvignons of the central Loire Valley. Full of incisive citrus fruit character, lifted herbaceous aromatics and cleansing acidity.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/HautPoitouSauvionWhiteWineFranceWhelehansWines_5000x.jpg?v=1663161643",
        price:18,
      },
      {
        id: 38,
        name: "VEGA SICILIA UNICO GRAN RESERVA, 2012",
        country: "SPAIN",
        category:"Red Wine",
        alcohol:"14.5 ",
        desc:"2012 is a concentrated, juicy, silky, and well-defined vintage. It is an expression that can be enjoyed immediately, but it will become incredible over time. Undoubtedly a big, generous wine, with sumptuously ripe fruit, vibrant with redcurrants and fine cedar. The essence of Unico is its ageing, and as a result the tannins are are well matured and despite its years it retains a youthful freshness",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/VegaSiciliaUnicoRedWineSpainWhelehansWines_5000x.png?v=1645541038",
        price:435,
      },
      {
        id: 39,
        name: "MARCHESI ANTINORI SOLAIA TOSCANA IGT, 2017",
        country: "ITALY",
        category:"Red Wine",
        alcohol:"14.5 ",
        desc:"The 2017 vintage was difficult with mixed weather, a bitter cold April followed later by a scorching August. But this Solaia was managed brilliantly, as evidenced by the critical applause; Decanter awarded it 97 points with Robertparker.com (95), the Wine Spectator (95) and Jancis Robinson (17.5/20) close behind. The blend of Cabernet Sauvignon (72%), Sangiovese (20%) and Cabernet Franc (8%) delivers an expressive nose of cherry and blackcurrant with well-mannered tannins and impeccable balance, said the Wine Spectator. Reflecting its 14% abv, it is a big wine graced with supreme elegance and balance.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/SolaiaAntinoriRedWineItalianWhelehansWines_5000x.png?v=1641651073",
        price:435,
      },
      {
        id: 40,
        name: "JOSEPH PHELPS VINEYARDS INSIGNIA, 2016",
        country: "USA",
        category:"Red Wine",
        alcohol:"14.5 ",
        desc:"The 2016 Insignia is fresh and focused on entry with expressive cocoa powder, graphite and earthy spices. Elegant and complex with a supple, creamy texture and bold tannins, this latest vintage offers luscious ripe plum and blackberry character with hints of roasted coffee and dark cherry throughout the palate to a long, velvety finish.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/JosephPhelpsInsigniaUSARedWineWhelehansWines_5000x.jpg?v=1637755646",
        price:415,
      },
      {
        id: 41,
        name: "E. GUIGAL CÔTE RÔTIE LA MOULINE, 2011",
        country: "FRANCE",
        category:"Red Wine",
        alcohol:"13 ",
        desc:"On the nose, small red fruits, blackberry and floral violet aromas. Intensely aromatic, powerful but full of finesse. It is supple on the palate with balance between the finesse of the aromas and an explosive richness due to the concentration of the wine. Greatly expressive of the terroir.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/GuigalMoulineCoteRotieFranceRedWineWhelehansWines_5000x.png?v=1637757704",
        price:460,
      },
      {
        id: 42,
        name: "CHÂTEAU D YQUEM - HALF BOTTLE, 2007",
        country: "FRANCE",
        category:"Red Wine",
        alcohol:"14 ",
        desc:"Legendary Chateau d'Yquem has been highly exalted since the middle ages when it was owned by the King of England who was also the Duke of Aquitaine. Today though it is owned by luxury conglomerate LVMH. It’s famed as the world’s not just Bordeaux’s finest sweet wine capable of ageing for 100 years or more. It was the only Sauternes rated as a premier cru supérieur in the famous 1855 classification.",
        img:"https://cdn.shopify.com/s/files/1/0353/6859/9683/products/YquemSauternesDessertWineFranceWhelehansWines_5000x.png?v=1623679186",
        price:380,
      },

      
  ];

  export default Product;